<!doctype html><html lang="id"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Threads Tools</title>
<style>
:root{font:14px system-ui;color:#e8eeff;background:#0a1020}*{box-sizing:border-box}body{margin:0}header{padding:18px 4%;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #2c3c59}nav{display:flex;gap:14px;flex-wrap:wrap;padding:16px 4%;position:sticky;top:0;background:#0a1020}a{color:#92bcff}main{max-width:1400px;margin:auto;padding:0 4% 70px}section{margin:24px 0;padding:20px;background:#131d33;border:1px solid #273653;border-radius:16px}h1,h2,h3{margin:0 0 14px}p{color:#aebcda}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.card{padding:16px;background:#1b2943;border-radius:12px;min-width:0}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}input,select,textarea,button{font:inherit;padding:9px;border-radius:8px;max-width:100%}input,select,textarea{background:#0c1529;border:1px solid #3a4e70;color:#eef3ff}textarea{width:100%;min-height:92px}button{background:#578ce8;border:0;color:white;cursor:pointer}button:hover{background:#75a8f8}form{margin:7px 0}.muted{color:#b5bfd4;font-size:12px}.badge{border:1px solid #6687b8;border-radius:99px;padding:2px 8px;font-size:11px;white-space:nowrap}img{max-width:110px;max-height:90px;object-fit:cover;border-radius:6px}label{display:block;margin:8px 0}summary{cursor:pointer}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #33415d;text-align:left;padding:8px}.scroll{overflow:auto}@media(max-width:620px){header{align-items:start;gap:10px}nav{position:static}.card{padding:12px}}
</style>
<header><div><h1>Threads Tools</h1><span class="muted">Publishing & community dashboard</span></div><form action="/logout" method="post">@csrf<button>Keluar</button></form></header>
<nav><a href="#accounts">Accounts</a><a href="#campaigns">Campaigns</a><a href="#posts">Posts</a><a href="#media">Media</a><a href="#telegram">Telegram</a><a href="#logs">Activity</a></nav>
<main>
@if(session('notice'))<section>{{session('notice')}}</section>@endif
@if($errors->any())<section style="color:#ffabab">@foreach($errors->all() as $error)<div>{{$error}}</div>@endforeach</section>@endif
<section><h2>Overview</h2><div class="grid"><div class="card">Accounts <h2>{{$accounts->count()}}</h2>Ready {{$accounts->where('status','READY')->count()}}</div><div class="card">Campaigns <h2>{{$campaigns->count()}}</h2>Drafts {{$posts->where('status','DRAFT')->count()}}</div><div class="card">Publishing <h2>{{$posts->where('status','PUBLISHED')->count()}}</h2>Queued {{$posts->where('status','QUEUED')->count()}}</div><div class="card">Transaction approvals <h2>{{$feed->where('status','PENDING_APPROVAL')->count()}}</h2></div></div></section>
<section id="accounts"><div class="row"><h2>Threads Accounts</h2><form action="/accounts" method="post">@csrf<button>+ Add Account</button></form></div><p>Browser login terbuka di desktop server. Selesaikan login dan verifikasi sendiri, kemudian cek session.</p><div class="grid">@foreach($accounts as $a)<div class="card"><h3>{{'@'.($a->username ?? 'account-'.$a->id)}}</h3><span class="badge">{{$a->status}}</span><form action="/accounts/{{$a->id}}/login" method="post">@csrf<button>Ulangi Login</button></form><form action="/accounts/{{$a->id}}/check" method="post">@csrf<button>Check Session</button></form><small class="muted">{{$a->last_error}}</small></div>@endforeach</div></section>
<section id="campaigns"><h2>Campaigns</h2><form method="post" action="/campaigns" class="row">@csrf<input name="name" placeholder="Nama campaign" required><input name="product_name" placeholder="Produk"><input name="notes" placeholder="Catatan"><button>Buat Campaign</button></form><div class="grid">@foreach($campaigns as $c)<div class="card"><h3>{{$c->name}}</h3><p>{{$c->product_name}}</p><form action="/campaigns/{{$c->id}}/duplicate" method="post">@csrf<label>Pilih akun untuk draft:</label><div class="row">@foreach($accounts as $a)<label><input type="checkbox" name="account_ids[]" value="{{$a->id}}"> {{'@'.($a->username??$a->id)}}</label>@endforeach</div><button>Duplicate to selected</button></form></div>@endforeach</div></section>
<section id="media"><h2>Media Library</h2><form action="/media" method="post" enctype="multipart/form-data" class="row">@csrf<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required><select name="campaign_id"><option value="">Umum</option>@foreach($campaigns as $c)<option value="{{$c->id}}">{{$c->name}}</option>@endforeach</select><button>Upload</button></form><div class="row">@foreach($media as $m)<div class="card"><img src="/media/{{$m->id}}" alt="{{$m->original_name}}"><p>#{{$m->id}} {{$m->original_name}}</p></div>@endforeach</div></section>
<section id="posts"><h2>Post Editor</h2><p>Simpan perubahan lalu approve sebelum masuk queue. Media diurutkan sesuai urutan ID yang dipilih.</p><div class="grid">@foreach($posts as $p)<div class="card"><div class="row"><h3>#{{$p->id}} {{'@'.($p->username??$p->threads_account_id)}}</h3><span class="badge">{{$p->status}}</span></div><p>Campaign #{{$p->campaign_id}} · {{$p->account_status}}</p>@if(in_array($p->status,['DRAFT','READY','APPROVED','FAILED']))<form action="/posts/{{$p->id}}" method="post">@csrf<textarea name="caption" placeholder="Caption" required>{{$p->caption}}</textarea><label>Schedule (kosong = segera) <input type="datetime-local" name="scheduled_at" value="{{ $p->scheduled_at ? \Illuminate\Support\Carbon::parse($p->scheduled_at)->format('Y-m-d\TH:i') : '' }}"></label><label>Media (Ctrl/⌘ untuk memilih beberapa)</label><select name="media_ids[]" multiple size="4" style="width:100%">@foreach($media as $m)<option value="{{$m->id}}">#{{$m->id}} {{$m->original_name}}</option>@endforeach</select><button>Simpan Draft</button></form>@endif
@if(in_array($p->status,['READY','APPROVED']))<form method="post" action="/posts/{{$p->id}}/approve">@csrf<button>{{$p->status==='READY'?'Approve':'Unapprove'}}</button></form>@endif
@if($p->status==='APPROVED')<form method="post" action="/posts/{{$p->id}}/queue">@csrf<button>Queue Publish</button></form>@endif
@if($p->last_error)<p style="color:#ffa2a2">{{$p->last_error}}</p>@endif @if($p->published_url)<a href="{{$p->published_url}}" target="_blank" rel="noopener noreferrer">Lihat post</a>@endif</div>@endforeach</div></section>
<section id="telegram"><h2>Telegram</h2><div class="grid"><div class="card"><h3>Groups</h3><form action="/telegram/groups" method="post">@csrf<input name="name" placeholder="Group name" required><input name="chat_id" placeholder="-100..." required><button>Tambah Group</button></form>@foreach($groups as $g)<p>{{$g->name}} · {{$g->chat_id}}</p>@endforeach</div><div class="card"><h3>Community Templates</h3><form action="/telegram/templates" method="post">@csrf<input name="name" placeholder="Judul" required><select name="kind"><option>FAQ</option><option>ANNOUNCEMENT</option><option>SIMULATION</option></select><textarea name="body" placeholder="Konten" required></textarea><button>Simpan</button></form>@foreach($templates as $t)<details><summary>{{$t->name}} · {{$t->kind}}</summary><p style="white-space:pre-wrap">{{$t->body}}</p><form action="/telegram/templates/{{$t->id}}/send" method="post">@csrf<select name="group_id">@foreach($groups as $g)<option value="{{$g->id}}">{{$g->name}}</option>@endforeach</select><button>Kirim</button></form></details>@endforeach</div></div><h3>Verified Transaction Feed</h3><p>Hanya webhook ber-HMAC dari website order setelah status PAID yang dapat membuat entri. Seluruhnya perlu approval.</p><div class="grid">@foreach($feed as $f)<div class="card"><b>Order #{{$f->external_order_id}}</b><p>{{$f->product}} · Rp{{number_format($f->amount_idr,0,',','.')}}</p><span class="badge">{{$f->status}}</span>@if($f->status==='PENDING_APPROVAL')<form action="/telegram/feed/{{$f->id}}/approve" method="post">@csrf<button>Approve</button></form>@elseif($f->status==='APPROVED')<form action="/telegram/feed/{{$f->id}}/send" method="post">@csrf<button>Kirim ke Telegram</button></form>@endif @if($f->last_error)<p>{{$f->last_error}}</p>@endif</div>@endforeach</div></section>
<section id="logs"><h2>Activity Log</h2><div class="scroll"><table><thead><tr><th>Waktu</th><th>Post</th><th>Step</th><th>Status</th><th>Detail</th></tr></thead><tbody>@foreach($logs as $l)<tr><td>{{$l->created_at}}</td><td>{{$l->campaign_post_id}}</td><td>{{$l->step}}</td><td>{{$l->status}}</td><td>{{$l->detail}}</td></tr>@endforeach</tbody></table></div></section>
</main></html>
